### ISSUE TITLE
Replace `statefulMapConcat` with `statefulMap` + `mapConcat` in codebase

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-connectors#307] opened 2024-01-03 07:51 UTC
As the title suggests, `statefulMapConcat` is deprecated so it should replaced with `statefulMap` + `mapConcat` so that the 1.1.0 version of pekko-http isn't relying on deprecated pekko methods.

**Comment by pjfanning** [comment] 2024-01-03 09:33
duplicate of https://github.com/apache/incubator-pekko-connectors/issues/294

**Closed by pjfanning** 2024-01-03 09:33 UTC
